Remove the ClusterRole aggregation from the default manifests
tektoncd/dashboard pull request #2059
Opened 2021-05-24 22:39 UTC by AlanGreene

# Changes

Closes https://github.com/tektoncd/dashboard/issues/2047

ClusterRole aggregation is only used to support Dashboard extensions
and requires additional permissions on the cluster. This causes
problems in many scenarios and currently affects all users even if
they're not using extensions.

Move the aggregation rule behind an installer flag so users who
need it can still easily generate the required config but other
users benefit from the reduced permissions required for a default
install.

Document the flag in the extensions doc and describe the requirements
for achieving the same result manually for users not using the
installer script.

Also update the installer docs and help command to describe the
new option.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/main/CONTRIBUTING.md)
for more details._

2021-05-25 14:00 UTC, AlanGreene commented
/test pull-tekton-dashboard-integration-tests

2021-05-25 15:33 UTC, AlanGreene commented
/test pull-tekton-dashboard-integration-tests

2021-05-25 15:54 UTC, AlanGreene commented
/test pull-tekton-dashboard-integration-tests

2021-05-25 16:36 UTC, AlanGreene commented
/test pull-tekton-dashboard-build-tests

2021-05-25 17:04 UTC, AlanGreene commented
/test pull-tekton-dashboard-integration-tests

2021-05-25 17:32 UTC, AlanGreene commented
/test pull-tekton-dashboard-integration-tests

2021-05-25 18:39 UTC, AlanGreene commented
/test pull-tekton-dashboard-integration-tests

2021-05-26 15:47 UTC, briangleeson requested changes
Couple of comments on Strings

2021-05-26 15:47 UTC, briangleeson commented on docs/dev/installer.md
> +        [--external-logs <logs-provider-url>]   External url to fetch logs from when not available in the cluster
I feel like this sentence doesnt read right: `External url to fetch logs from when not available in the cluster`

Better? `External url from which to fetch logs, when logs are not available in the cluster`

2021-05-26 15:47 UTC, briangleeson commented on docs/extensions.md
> +Alternatively, if the `--extensions-rbac` is not used, ommit the label from the ClusterRole, and define the appropriate RoleBinding or ClusterRoleBinding yourself with the subject set to the `tekton-
Typo for `omit`

2021-05-26 15:47 UTC, briangleeson commented on scripts/installer
> +  echo -e "\t[--external-logs <logs-provider-url>]\tExternal url to fetch logs from when not available in the cluster"
Same comment as before with wording of this sentence

2021-05-26 15:52 UTC, AlanGreene commented on docs/extensions.md
> +Alternatively, if the `--extensions-rbac` is not used, ommit the label from the ClusterRole, and define the appropriate RoleBinding or ClusterRoleBinding yourself with the subject set to the `tekton-
🙈

2021-05-26 15:59 UTC, briangleeson commented
/lgtm

2021-05-26 16:43 UTC, AlanGreene commented
/test tekton-dashboard-unit-tests

2021-05-26 17:15 UTC, AlanGreene commented
/test tekton-dashboard-unit-tests

2021-05-26 18:54 UTC, AlanGreene commented
/test tekton-dashboard-unit-tests

2021-05-26 23:17 UTC, AlanGreene commented
/test pull-tekton-dashboard-integration-tests

2021-05-26 23:34 UTC, merged