enable Dashboard iframe loading with flag
tektoncd/dashboard pull request #2101
Opened 2021-06-24 08:36 UTC by leiyanggz

The value of the response header "X-Frame-Options" is "deny" by default in http requests because of security concerns. 
However in some use cases people want to load the dashboard in their internal web applications via iframe.  

# Changes

Add an additional boolean flag to disable the header "X-Frame-Options".

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/main/CONTRIBUTING.md)
for more details._

2021-06-24 18:02 UTC, AlanGreene requested changes
Thanks for the PR @leiyanggz. I've left a suggestion to make this a little more flexible while still allowing users to disable it. Let me know if you have any questions.

2021-06-24 18:24 UTC, leiyanggz commented on cmd/dashboard/main.go
> +	enableXframe       = flag.Bool("enable-xframe", false, "Whether or not a browser should be allowed to render a page in a <frame>, <iframe>, <embed> or <object>")
Got it. Will do.

2021-06-25 07:20 UTC, leiyanggz commented on cmd/dashboard/main.go
> +	enableXframe       = flag.Bool("enable-xframe", false, "Whether or not a browser should be allowed to render a page in a <frame>, <iframe>, <embed> or <object>")
Please take a look at the new pull request https://github.com/tektoncd/dashboard/pull/2104

2021-06-25 07:20 UTC, closed without merging

2021-06-25 07:21 UTC, leiyanggz commented
Close the pull request since new pull request submitted https://github.com/tektoncd/dashboard/pull/2104