Fix error in PipelineRun, Task, and TaskTree stories
tektoncd/dashboard pull request #2211
Opened 2021-09-27 16:05 UTC by AlanGreene

# Changes

Fix 'invalid hook call' errors in the PipelineRun, Task, and TaskTree
stories that currently prevent them from rendering. This appears to be
caused by some unusual behaviour in Storybook relating to the default
wrapper component in the latest release.

Wrapping the affected stories in a simple decorator that just renders the
story unmodified resolves the error.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/main/CONTRIBUTING.md)
for more details._

2021-09-27 16:43 UTC, briangleeson requested changes
tiny nit, otherwise good

2021-09-27 16:43 UTC, briangleeson commented on .storybook/preview.js
> +      notes={context.parameters.notes}
Nit: alphabetical order the props

2021-09-28 09:31 UTC, AlanGreene commented on .storybook/preview.js
> +      notes={context.parameters.notes}
you got it 👍  done

2021-09-28 10:17 UTC, AlanGreene commented
npm install didn't run successfully, we'll need to update the scripts to bail when this happens for quicker feedback

/test pull-tekton-dashboard-integration-tests

2021-09-30 10:50 UTC, briangleeson approved these changes
/lgtm

2021-09-30 10:51 UTC, merged