Make title text readable by screen readers
tektoncd/dashboard pull request #2588
Opened 2022-11-18 19:09 UTC by kaushalnavneet

2022-11-21 12:35 UTC, AlanGreene requested changes
Thanks @kaushalnavneet, couple of small comments.
I've sent you instructions for resolving the EasyCLA check too, let me know if you have any questions.

/ok-to-test

2022-11-21 12:35 UTC, AlanGreene commented on packages/components/src/components/FormattedDate/FormattedDate.js
> +  formattedDate = formatTooltip(formattedDate)
You'll need to change `const` to `let` above since you're reassigning this.

2022-11-21 12:35 UTC, AlanGreene commented on packages/components/src/components/Tabs/Tabs.js
> +  selected ? <CarbonTabContent selected={selected} {...other} /> : <span></span>;
Shouldn't this pass the id to the span? We'll also need to include styles to ensure it's visibly hidden as we don't want unexpected content (even if it's just whitespace) appearing on the page and potentially affecting layout etc.

2022-11-22 01:28 UTC, kaushalnavneet commented
Closing. Opened a new PR - https://github.com/tektoncd/dashboard/pull/2594

2022-11-22 01:28 UTC, closed without merging