Update Portuguese with missing translations
tektoncd/dashboard pull request #3070
Opened 2023-08-22 06:26 UTC by FaahdSolano

# Changes

Added some portuguese translation (file src/nls/messages_pt.json) as described in issue #3068

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (new features, significant UI changes, API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

2023-08-22 09:38 UTC, AlanGreene commented
Thanks for the pR @FaahdSolano 
/ok-to-test

2023-08-22 09:56 UTC, AlanGreene requested changes

2023-08-22 09:56 UTC, AlanGreene commented on src/nls/messages_pt.json
> +  "dashboard.about.title": "Sobre Tekton",
```suggestion
  "dashboard.about.title": "Sobre Tekton",
```

Can you remove the trailing space at the end of this line? That should resolve the issue with the tests.

2023-08-22 11:59 UTC, AlanGreene commented
/kind misc

2023-08-22 19:26 UTC, AlanGreene requested changes
Looks like there's a trailing newline at the end of the file. Can you remove that and squash your commits please? Otherwise looks good, thanks for the translations.

2023-08-22 20:12 UTC, FaahdSolano commented
Thanks for the patience, first time contributing

2023-08-23 10:19 UTC, AlanGreene commented
> Thanks for the patience, first time contributing

No worries 😸 

Looks like the newline at the end is still there. Perhaps your editor is adding it automatically? If you're using an editor with support for [EditorConfig](https://editorconfig.org/#pre-installed), or that supports plugins providing this functionality, we have this set https://github.com/tektoncd/dashboard/blob/b766740b3f2fd91b3665973d193110062ea77941/.editorconfig#L18

Can you also squash your commits so there's just 1 commit in the PR? See the contributing guide: https://github.com/tektoncd/community/blob/main/standards.md#small-pull-requests
This helps us to maintain a clean and informative commit history.

2023-08-24 10:59 UTC, AlanGreene commented
The integration tests failure is unrelated to your change and should be resolved now
/test pull-tekton-dashboard-integration-tests

2023-08-31 09:43 UTC, AlanGreene commented
Thanks again for the translations @FaahdSolano. I've opened https://github.com/tektoncd/dashboard/pull/3098 which includes your changes and resolves the issue with the trailing newline.

2023-08-31 09:43 UTC, closed without merging