Add Create button and Edit and run buttons for CustomRuns
tektoncd/dashboard pull request #3108
Opened 2023-09-05 19:25 UTC by jisoolee

# Changes

The adding `Edit and run` feature for CustomRuns task was subdivided in 3 parts and this PR is related to the first one
- [x] Adding Create and Edit and run buttons
- [ ] Creating a Create page
- [ ] Connecting the buttons to the proper Create pages

Connect to https://github.com/tektoncd/dashboard/issues/2437

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (new features, significant UI changes, API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

2023-09-06 09:59 UTC, AlanGreene commented
Thanks @jisoolee. We need to make sure the Dashboard is always in a releasable state, so we'll either need to hide the buttons behind some kind of feature flag (query param or localStorage), or hold this PR until the create / edit page is merged first.

2023-09-06 12:55 UTC, jisoolee commented
@AlanGreene Thank you for review and comment. I understand, yes I was also worrying about the release schedule (if I could not completed all the tasks before the next release). Please hold this PR until I open other PRs to complete the feature.

2023-09-20 19:06 UTC, AlanGreene requested changes
There's a lot of code in this related to the form-based UI which we are not adding for CustomRuns. Once that's removed there may be some opportunities to simplify / cleanup the remaining code.

2023-09-20 21:55 UTC, jisoolee commented on src/containers/CreateCustomRun/CreateCustomRun.jsx
> +  return (
This part seems needed.
Without them, it shows when I tried to open Create page
<img width="1391" alt="image" src="https://github.com/tektoncd/dashboard/assets/6076531/f6769a54-c493-4565-9bfe-d37bf762bf62">

2023-09-20 22:00 UTC, jisoolee commented on src/containers/CreateCustomRun/CreateCustomRun.jsx
> +      nodeSelector: nodeSelector.length
Thank you Alan. I updated the fields but could you double check if they are ok? Or do I need to put `spec.` in front of the names as you mentioned above? (Also do I need to remove some more except the above 4+5 fields? such as `labels`)

2023-09-21 08:56 UTC, AlanGreene commented on src/containers/CreateCustomRun/CreateCustomRun.jsx
> +  return (
yes you must always return something from the render function
it looks like you have it right now, so it either returns the editor with the source run for a rerun, or the editor with the skeleton run for a new one 👍

2023-09-21 08:57 UTC, AlanGreene commented on src/containers/CreateCustomRun/CreateCustomRun.jsx
> +      nodeSelector: nodeSelector.length
`labels` is part of `metadata` so that's OK

2023-09-28 16:31 UTC, AlanGreene requested changes

2023-09-28 16:31 UTC, AlanGreene commented on src/containers/CustomRuns/CustomRuns.jsx
> +            );
For now we'll always have at least 1 query param (`mode=yaml`) so we can simplify this and always construct the query string using URLSearchParams:

```suggestion
            const queryString = new URLSearchParams({
                ...(namespace !== ALL_NAMESPACES && { namespace }),
                // currently default is yaml mode
                mode: 'yaml'
              }).toString();
            }
            navigate(urls.customRuns.create() + `?${queryString}`);
```

2023-09-28 16:31 UTC, AlanGreene commented on src/containers/CustomRuns/CustomRuns.jsx
> +          id: 'dashboard.cancelCustomRun.actionText',
No need to change this string, we can continue using the existing one:

```suggestion
          id: 'dashboard.cancelTaskRun.actionText',
```

2023-09-28 16:31 UTC, AlanGreene commented on src/containers/CustomRuns/CustomRuns.jsx
> +
These aren't used so they can be removed:

```suggestion
```

2023-09-28 16:31 UTC, AlanGreene commented on src/api/customRuns.js
> +  getTektonPipelinesAPIVersion,
This doesn't appear to be used

2023-09-28 16:31 UTC, AlanGreene commented on src/api/customRuns.js
> +  kind,
not used

2023-09-28 16:31 UTC, AlanGreene commented on src/api/customRuns.js
> +  }
As mentioned in [a previous review](https://github.com/tektoncd/dashboard/pull/3108#discussion_r1332042350), podTemplate and nodeSelector are not valid for a CustomRun so should be removed:
```suggestion
```

2023-09-28 16:31 UTC, AlanGreene commented on src/containers/CreateCustomRun/CreateCustomRun.jsx
> +  function checkFormValidation() {
There's still a lot of code in this component related to the form-based UI, for example, `checkFormValidation`, `handleAddLabel`, `handleNamespaceChange`, `handleSubmit`, etc.

These should all be removed. Then you can also remove any of the unused state, for example `initialParams`, `initialParamsState`, etc.

2023-09-28 16:31 UTC, AlanGreene commented on src/containers/CreateCustomRun/CreateCustomRun.jsx
> +  function handleClose() {
Doesn't look like this is used

2023-09-28 16:31 UTC, AlanGreene commented on src/containers/CreateCustomRun/CreateCustomRun.jsx
> +  }
These are all related to the form-based UI so are not needed.

2023-09-28 16:31 UTC, AlanGreene commented on src/containers/CreateCustomRun/CreateCustomRun.jsx
> +  }
Not used.

There may be more. Please review any remaining functions to ensure they're actually called, or remove them if they're no longer needed.

2023-09-29 15:14 UTC, AlanGreene requested changes
There's still quite a bit of unused code here that needs to be removed. I've added comments to the biggest pieces.

Most of this should have been caught by the linter so I'll have to debug that to figure out why it's not reporting errors.

For now you'll have to manually review each function, variable, and state field you've added to ensure they're actually used, and remove any that are not needed. When you remove a function, for example `handleSubmit`, check if there are additional functions or variables that can be cleaned up following its removal.

2023-09-29 15:14 UTC, AlanGreene commented on src/containers/CreateCustomRun/CreateCustomRun.jsx
> +  resourceNameRegex,
These aren't used and should be removed

2023-09-29 15:14 UTC, AlanGreene commented on src/containers/CreateCustomRun/CreateCustomRun.jsx
> +import { KeyValueList, Loading } from '@tektoncd/dashboard-components';
`KeyValueList` isn't used so the import should be removed
```suggestion
import { Loading } from '@tektoncd/dashboard-components';
```

2023-09-29 15:14 UTC, AlanGreene commented on src/containers/CreateCustomRun/CreateCustomRun.jsx
> +import { isValidLabel } from '../../utils';
Not used

2023-09-29 15:14 UTC, AlanGreene commented on src/containers/CreateCustomRun/CreateCustomRun.test.jsx
> +    });
Both of these are waiting for the same thing, you should be able to remove the second one.

Looks like this duplication is also in the CreatePipelineRun test, I've opened a PR to remove that one: https://github.com/tektoncd/dashboard/pull/3138

2023-09-29 15:14 UTC, AlanGreene commented on src/containers/CustomRuns/CustomRuns.jsx
> +  labels,
not used

2023-09-29 16:43 UTC, AlanGreene commented
For tracking purposes:

The issue with the linter not reporting issues was identified and resolved in https://github.com/tektoncd/dashboard/pull/3139

2023-09-29 19:36 UTC, jisoolee commented
/retest

2023-10-05 10:50 UTC, briangleeson requested changes

2023-10-05 10:50 UTC, briangleeson commented on src/containers/CreateCustomRun/CreateCustomRun.test.jsx
> +    //   expect(queryAllByText(/Loading/).length).toBe(0);
Is this test needed?

2023-10-05 10:50 UTC, briangleeson commented on src/containers/CreateCustomRun/CreateCustomRun.jsx
> +  });
```suggestion
  const [{ kind, labels, namespace, params }] = useState({
    ...initialState,
    customRef: '',
    kind: 'Custom',
    namespace: getNamespace()
  });
```

2023-10-05 13:43 UTC, briangleeson approved these changes
/lgtm

2023-10-05 13:46 UTC, briangleeson commented
/hold cancel

2023-10-05 13:47 UTC, briangleeson commented
/ok-to-test

2023-10-05 14:02 UTC, merged